apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clickhouse

resources:
  - ch-config.yaml
  - secrets.yaml
  - ssl-certs.yaml
  - clickhouse.yaml

# configMapGenerator:
#   - name: clickhouse-config
#     files:
#       - configs/ssl.xml
#       - configs/storage.xml
#       - configs/logging.xml
#       - configs/network.xml