# ClickHouse Keeper Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-keeper-config
  namespace: clickhouse
data:
  keeper.xml: |
    <clickhouse>
      <logger>
        <level>information</level>
        <console>true</console>
      </logger>
      
      <listen_host>0.0.0.0</listen_host>
      
      <keeper_server>
        <tcp_port>9181</tcp_port>
        <server_id from_env="KEEPER_SERVER_ID"/>
        
        <log_storage_path>/var/lib/clickhouse/coordination/log</log_storage_path>
        <snapshot_storage_path>/var/lib/clickhouse/coordination/snapshots</snapshot_storage_path>
        
        <coordination_settings>
          <operation_timeout_ms>10000</operation_timeout_ms>
          <session_timeout_ms>30000</session_timeout_ms>
          <raft_logs_level>information</raft_logs_level>
          <rotate_log_storage_interval>10000</rotate_log_storage_interval>
          <snapshots_to_keep>3</snapshots_to_keep>
          <shutdown_timeout>5000</shutdown_timeout>
          <startup_timeout>10000</startup_timeout>
        </coordination_settings>
        
        <raft_configuration>
          <server>
            <id>1</id>
            <hostname>clickhouse-keeper-0.clickhouse-keeper.clickhouse.svc.cluster.local</hostname>
            <port>9234</port>
          </server>
          <server>
            <id>2</id>
            <hostname>clickhouse-keeper-1.clickhouse-keeper.clickhouse.svc.cluster.local</hostname>
            <port>9234</port>
          </server>
          <server>
            <id>3</id>
            <hostname>clickhouse-keeper-2.clickhouse-keeper.clickhouse.svc.cluster.local</hostname>
            <port>9234</port>
          </server>
        </raft_configuration>
      </keeper_server>
    </clickhouse>

---
# Init script to set KEEPER_SERVER_ID
apiVersion: v1
kind: ConfigMap
metadata:
  name: keeper-init-script
  namespace: clickhouse
data:
  init.sh: |
    #!/bin/bash
    [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
    export KEEPER_SERVER_ID=$((${BASH_REMATCH[1]} + 1))
    echo "KEEPER_SERVER_ID=${KEEPER_SERVER_ID}"
