apiVersion: v1
kind: Service
metadata:
  name: clickhouse-keeper
  labels:
    app: clickhouse-keeper
spec:
  ports:
    - port: 9181
      name: client
    - port: 9234
      name: raft
  clusterIP: None
  selector:
    app: clickhouse-keeper