apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clickhouse

resources:
  - ../../base/operator/
  - ../../base/ch-keeper/
  - ../../base/ch-install/

# patches:
#   - path: storage.yaml
#     target:
#       kind: ClickHouseInstallation
#       name: clickhouse-ha