apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka-dev # Deploys this stack to the 'kafka-dev' namespace
resources:
- ../../base
- kafka-cluster.yaml
- kafka-nodepool.yaml
patches:
- path: patch-operator-namespace.yaml
