apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka-prod
resources:
- ../../base
- storage/
- user/
- topic/
- metrics/
patches:
- path: patch-operator-namespace.yaml
- path: patch-kafka-cluster.yaml
- path: patch-kafka-nodepool.yaml