apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka-prod
resources:
- ../../base
patches:
- path: patch-operator-namespace.yaml
- path: patch-kafka.yaml
- path: patch-kafka-nodepool.yaml